// Auto-generated by scripts/get-content-dates.mjs - do not edit
// Maps content slug -> last git commit date (YYYY-MM-DD)
export const CONTENT_DATES: Record<string, string> = {
  "building-lifeos": "%Y->- (HEAD -> main, origin/main)",
  "rag-agents-product": "%Y->- (HEAD -> main, origin/main)",
  "useful-ai-beyond-demos": "%Y->- (HEAD -> main, origin/main)",
  "what-productivity-means-with-ai": ""
};
