import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight } from 'lucide-react';
import { FLAGSHIP_PROJECTS } from '../lib/projects';
import { WRITING } from '../lib/writing';
import '../studio.css';

const perspectives = [
  ['The engineer', 'Systems that work.', 'Retrieval, agents, evaluation and the decisions that make AI useful in production.'],
  ['The creative', 'Stories worth making.', 'Connecting audience evidence and creative tools to the stories people care about.'],
  ['The builder', 'Ideas worth testing.', 'Finding a real problem, building something usable, and learning what changes behavior.'],
];

export function Home() {
  const [lens, setLens] = useState(0);
  const selected = FLAGSHIP_PROJECTS.filter(p => ['enterprise-knowledge-agent','multimodal-film-stack','research-gap-finder'].includes(p.slug));
  return <div className="studio-home">
    <section className="editorial-hero"><div className="eyeline"><span>SUBANDHU AGRAVANSHI</span><span>AI ENGINEER / PRODUCT BUILDER</span></div><div className="hero-grid"><div><h1>Curiosity,<br/>with a <em>shipping habit.</em></h1><p>I build AI systems and explore what they make possible. My work lives where engineering meets entertainment, human behavior, and a useful business idea.</p><div className="hero-actions"><Link className="paper-button" to="/projects">Explore the work <ArrowUpRight size={18}/></Link><Link to="/about">Meet the person ↗</Link></div></div><div className={`perspective lens-${lens}`}><div className="lens-art" aria-hidden="true"><i/><i/><i/></div><span className="eyeline">ONE CURIOSITY. THREE PERSPECTIVES.</span><div className="lens-controls">{perspectives.map((p,i)=><button key={p[0]} aria-pressed={lens===i} onClick={()=>setLens(i)}>{p[0]}</button>)}</div><div className="lens-copy" aria-live="polite"><h2>{perspectives[lens][1]}</h2><p>{perspectives[lens][2]}</p></div></div></div><div className="hero-foot"><span>Production AI · Retrieval & agents · Generative media</span><a href="mailto:subandwho@gmail.com">Open to thoughtful conversations ↗</a></div></section>
    <section className="editorial-section"><div className="section-top"><div><span className="eyeline">01 / THE PRODUCT NOTEBOOK</span><h2>Two questions I keep coming back to.</h2></div><Link to="/studio">Inside the builds ↗</Link></div><div className="experiment-grid"><Link to="/studio#fanpulse" className="experiment fp-experiment"><span className="eyeline">ENTERTAINMENT × INTELLIGENCE</span><h3>fanPulse<em>Follow the signal.</em></h3><p>What if audience evidence could help us decide what to create—and why?</p><div className="signal" aria-hidden="true">{Array.from({length:9},(_,i)=><i key={i}/>)}</div><div className="experiment-foot"><span>LOCAL PROTOTYPE · QUALITY VALIDATION NEXT</span><ArrowUpRight/></div></Link><Link to="/studio#productivity" className="experiment po-experiment"><span className="eyeline">PERSONAL CONTEXT × EVERYDAY ACTION</span><h3>Productivity OS<em>A little more room.</em></h3><p>What if a simple note could become the right next step, without another planning ritual?</p><div className="little-day" aria-hidden="true"><span>Capture a thought</span><span>Make room for it</span><span>Take one small step</span></div><div className="experiment-foot"><span>LOCAL PROTOTYPE · IOS DIRECTION</span><ArrowUpRight/></div></Link></div><p className="editorial-note">Working hypotheses, implemented foundations, and open questions. No invented adoption or impact numbers.</p></section>
    <section className="editorial-section"><div className="section-top"><div><span className="eyeline">02 / SELECTED ENGINEERING</span><h2>From ambiguity to implementation.</h2></div><Link to="/projects">All projects ↗</Link></div>{selected.map((p,i)=><Link className="work-row" to={`/projects/${p.slug}`} key={p.slug}><span className="work-number">0{i+1}</span><div><span className="eyeline">{p.lane}</span><h3>{p.title}</h3><p>{p.tagline}</p></div><ArrowUpRight/></Link>)}</section>
    <section className="editorial-section"><span className="eyeline">03 / HOW I WORK</span><h2>A hypothesis is a beginning.<br/><em>The result gets a vote.</em></h2><div className="thinking-grid">{[['ASK','Find the actual friction.','Start with a real workflow, its constraints, and the person trying to get something done.'],['BUILD','Make the idea testable.','Connect data, models and interfaces into a working loop. Keep the implementation explainable.'],['LEARN','Keep an honest record.','Measure quality, cost and behavior. Separate a functioning system from a product people want.']].map(p=><article key={p[0]}><span className="eyeline">{p[0]}</span><h3>{p[1]}</h3><p>{p[2]}</p></article>)}</div></section>
    <section className="editorial-section"><div className="section-top"><div><span className="eyeline">04 / NOTES FROM THE WORK</span><h2>Thinking out loud.</h2></div><Link to="/writing">All writing ↗</Link></div><div className="thinking-grid writing-cards">{WRITING.slice(0,3).map(w=><Link to={`/writing/${w.slug}`} key={w.slug}><span className="eyeline">{w.category}</span><h3>{w.title}</h3><p>{w.excerpt}</p><ArrowUpRight size={18}/></Link>)}</div></section>
    <section className="editorial-section contact-section"><span className="eyeline">LET'S COMPARE NOTES.</span><h2>Building something<br/><em>worth caring about?</em></h2><a className="paper-button" href="mailto:subandwho@gmail.com">Say hello <ArrowUpRight size={20}/></a><Link to="/experience">Explore my experience →</Link></section>
  </div>;
}
