import { Link } from 'react-router-dom';
import { useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import '../studio.css';

export function Studio() {
  const {hash} = useLocation();
  useEffect(()=>{if(hash)document.getElementById(hash.slice(1))?.scrollIntoView();},[hash]);
  return <div className="studio-home studio-page"><section className="editorial-section"><span className="eyeline">THE PRODUCT NOTEBOOK / SEPTEMBER 2026</span><h1>Build. Observe.<br/><em>Change your mind.</em></h1><p className="studio-lead">Two independent products exploring how AI can help people create with better evidence and act with less planning overhead.</p><p className="editorial-note">Stage: local prototypes. Public product demos are not yet available. Source repositories are intended to remain private during development.</p></section>
  <section id="fanpulse" className="editorial-section"><span className="eyeline">01 / FANPULSE</span><h2>From audience noise<br/>to creative decisions.</h2><div className="case-grid"><div><h3>The hypothesis</h3><p>Creative teams have abundant commentary but limited time to establish what matters. A project-aware workspace could connect evidence, uncertainty and experiments to their actual budget and ambitions.</p><h3>A concrete test</h3><p>A solo game developer with $5,000 asks what to learn from comparable games. The product should identify supported observations, disclose missing data and suggest feasible experiments.</p><h3>The working loop</h3><p>Project context → source excerpts → research job → citation checks → brief history → creative draft and revision. Character conversations use the selected story canon.</p></div><div><h3>Implemented locally</h3><ul><li>Independent desktop workspace and persistent project records.</li><li>Evidence provenance, deduplication and exact-quote validation.</li><li>Ollama-backed research and creative job paths with visible failures.</li><li>Configurable Reddit OAuth search and local scheduled watches.</li><li>Story versions, revision diffs and canon-scoped dialogue.</li></ul><h3>Still to validate</h3><p>Live connector access and model quality need integration testing. A matching quote does not establish causation. Monitoring breadth, useful insight quality and willingness to pay remain experiments.</p><h3>Next evidence</h3><p>Can five developers use a brief to change a real decision? Do repeated runs add useful information? What does a useful result cost?</p></div></div><p className="case-note">Earlier iteration: <Link to="/projects/fanpulse">the existing fanPulse research pipeline →</Link> Historical results belong to that implementation, not this studio.</p></section>
  <section id="productivity" className="editorial-section"><span className="eyeline">02 / PRODUCTIVITY OS</span><h2>Less organizing.<br/>More room for living.</h2><div className="case-grid"><div><h3>The hypothesis</h3><p>A notes-first companion could preserve personal context and turn everyday captures into realistic next steps, without asking people to become expert planners.</p><h3>A concrete test</h3><p>A busy professional balances work, a learning goal and a business idea. They leave a note, correct any mistaken interpretation, and get a plan that fits available time and energy.</p><h3>The working loop</h3><p>Original note → structured extraction → editable items and memory → explicit constraints → feasible plan → partial progress and replanning. Categories follow the user rather than a hardcoded curriculum.</p></div><div><h3>Implemented locally</h3><ul><li>Distinct notes and Today dashboard surfaces.</li><li>Persistent captures, tasks, goals, ideas and project categories.</li><li>Model-backed organization with original notes preserved.</li><li>Confirmed versus suggested memory and correction controls.</li><li>Planning around entered busy times, capacity and energy.</li><li>Partial progress and visibly deferred work.</li></ul><h3>Still to validate</h3><p>Calendar, email, Notion sync and native iOS widgets are future integration work. The prototype does not infer mental health from activity timestamps. We need to test whether it actually reduces planning effort.</p><h3>Next evidence</h3><p>Measure planning time, capture corrections and useful interventions over seven days. Success is meaningful progress, not more time inside the app.</p></div></div><p className="case-note">Earlier iteration: <Link to="/projects/lifeos">LifeOS and its gateway assistant →</Link> This companion explores a simpler product experience.</p></section>
  <section className="editorial-section"><span className="eyeline">THE JOURNEY / DECISION LOG</span><div className="thinking-grid">{[['01 · OBSERVATION','A working integration was not enough.','The earlier OpenWebUI path demonstrated plumbing. Everyday use still exposed gaps in memory, routing and usefulness.'],['02 · DECISION','Separate the experiences.','Entertainment needs a rich research studio. Personal productivity needs a quiet companion. Combining them compromised both.'],['03 · EXPERIMENT','Complete a useful loop.','Validate evidence-to-brief and capture-to-plan behavior before expanding infrastructure or claiming market demand.']].map(x=><article key={x[0]}><span className="eyeline">{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><p className="editorial-note">Engineering tests validate specific behavior. They do not establish product-market fit. Founder-recorded demos and measured pilot outcomes will be added as they exist.</p></section></div>;
}
